# Generated by Django 4.2.1 on 2023-06-14 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان دسته بندی')),
                ('slug', models.SlugField(max_length=100, verbose_name='آدرس دسته بندی')),
                ('status', models.BooleanField(default=True, verbose_name='آیا نمایش داده شود؟')),
            ],
            options={
                'verbose_name': 'دسته بندی صفحه داخلی',
                'verbose_name_plural': 'دسته بندی های صفحه داخلی',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='نام صفحه داخلی')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='آدرس صفحه داخلی')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('thumbnail', models.ImageField(upload_to='images', verbose_name='تصویر شاخص')),
                ('status', models.CharField(choices=[('d', 'پیش نویس'), ('p', 'منتشر شده')], max_length=1, verbose_name='آیا نمایش داده شود؟')),
                ('position', models.IntegerField(verbose_name='ترتیب نمایش')),
                ('category', models.ManyToManyField(to='pages.pagecategory', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'صفحه داخلی',
                'verbose_name_plural': 'صفحات داخلی',
            },
        ),
    ]
