# Generated by Django 4.2.1 on 2023-06-22 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام و نام خانوادگی')),
                ('mobile', models.IntegerField(default=True, max_length=11, verbose_name='موبایل')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('comment', models.TextField(verbose_name='دیدگاه')),
            ],
            options={
                'verbose_name': 'تماس با ما',
                'verbose_name_plural': 'تماس های ما',
            },
        ),
    ]
