# Generated by Django 4.2.1 on 2023-06-25 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='mobile',
        ),
        migrations.AddField(
            model_name='contact',
            name='message',
            field=models.TextField(default=None, verbose_name='پیام'),
        ),
    ]
