# Generated by Django 4.2.1 on 2023-07-01 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_alter_contact_email_alter_contact_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(error_messages={'invalid': ' لطفا یک ایمیل معتبر وارد نمایید!', 'max_length': 'تعداد کرکترهای ورودی بیشتر از حد مجاز است!', 'min_length': 'تعداد کرکترهای ورودی کمتر از حد مجاز است!', 'required': ' لطفا این فیلد را پر نمایید!'}, max_length=254, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(default=None, error_messages={'invalid': ' لطفا یک ایمیل معتبر وارد نمایید!', 'max_length': 'تعداد کرکترهای ورودی بیشتر از حد مجاز است!', 'min_length': 'تعداد کرکترهای ورودی کمتر از حد مجاز است!', 'required': ' لطفا این فیلد را پر نمایید!'}, verbose_name='پیام'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(error_messages={'invalid': ' لطفا یک ایمیل معتبر وارد نمایید!', 'max_length': 'تعداد کرکترهای ورودی بیشتر از حد مجاز است!', 'min_length': 'تعداد کرکترهای ورودی کمتر از حد مجاز است!', 'required': ' لطفا این فیلد را پر نمایید!'}, max_length=100, verbose_name='نام و نام خانوادگی'),
        ),
    ]
