# Generated by Django 4.2.1 on 2023-06-11 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_portfolio_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='آدرس دسته بندی'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='status',
            field=models.CharField(choices=[('d', 'پیش نویس'), ('p', 'منتشر شده')], max_length=1, verbose_name='وضعیت نمایش'),
        ),
        migrations.CreateModel(
            name='PortfolioCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان دسته بندی')),
                ('slug', models.SlugField(max_length=100, verbose_name='آدرس دسته بندی')),
                ('status', models.BooleanField(default=True, verbose_name='آیا نمایش داده شود؟')),
                ('position', models.IntegerField(verbose_name='موقعیت')),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child', to='portfolio.portfoliocategory', verbose_name='زیردیته')),
            ],
            options={
                'verbose_name': 'دسته بندی نمونه کار',
                'verbose_name_plural': 'دسته یندی های نمونه کار',
                'ordering': ['parent__id', 'position'],
            },
        ),
        migrations.AddField(
            model_name='portfolio',
            name='category',
            field=models.ManyToManyField(to='portfolio.portfoliocategory', verbose_name='دسته بندی'),
        ),
    ]
