# Generated by Django 4.2.1 on 2023-06-14 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_portfolio_slug_alter_portfolio_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliocategory',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child', to='portfolio.portfoliocategory', verbose_name='زیردسته'),
        ),
    ]
