# Generated by Django 4.2.1 on 2023-06-14 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان دسته بندی')),
                ('slug', models.SlugField(max_length=100, verbose_name='آدرس دسته بندی')),
                ('status', models.BooleanField(default=True, verbose_name='آیا نمایش داده شود؟')),
                ('position', models.IntegerField(verbose_name='ترتیب نمایش')),
                ('innerpages', models.IntegerField(verbose_name='در صفحات داخلی نمایش داده شود؟')),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child', to='menu.menucategory', verbose_name='زیردسته')),
            ],
            options={
                'verbose_name': 'دسته بندی منو',
                'verbose_name_plural': 'دسته بندی های منو',
                'ordering': ['parent__id', 'position'],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='نام منو')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='آدرس منو')),
                ('ShortDescription', models.TextField(verbose_name='توضیح مختصر')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('thumbnail', models.ImageField(upload_to='images', verbose_name='تصویر شاخص')),
                ('status', models.CharField(choices=[('d', 'پیش نویس'), ('p', 'منتشر شده')], max_length=1, verbose_name='آیا نمایش داده شود؟')),
                ('footer', models.IntegerField(verbose_name='در فوتر نمایش داده شود؟')),
                ('position', models.IntegerField(verbose_name='ترتیب نمایش')),
                ('category', models.ManyToManyField(to='menu.menucategory', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'منو',
                'verbose_name_plural': 'منوها',
            },
        ),
    ]
