# Generated by Django 4.2.1 on 2023-06-14 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_rename_shortdescription_menu_shortdescription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='category',
            field=models.ManyToManyField(to='menu.menucategory', verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='footer',
            field=models.CharField(choices=[('n', 'نمایش داده نشود'), ('y', 'نمایش داده شود')], max_length=1, verbose_name='وضعیت نمایش در فوتر'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='status',
            field=models.CharField(choices=[('d', 'پیش نویس'), ('p', 'منتشر شده')], max_length=1, verbose_name='وضعیت نمایش'),
        ),
    ]
