# Generated by Django 4.2.1 on 2023-06-18 16:57

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_menu_category_alter_menu_footer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='menucategory',
            name='innerpages',
            field=models.BooleanField(verbose_name='نمایش در صفحات داخلی'),
        ),
    ]
